site_name: Andromeda

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python

nav:
  - 'Home':
    - 'Overview': overview.md
    - 'Installation': installation.md
    - 'Quickstart': quickstart.md
    - 'Contributing': contributing.md
  - 'User Guide':
    - 'Model': model.md