name: macOS

on:
  push:
    branches:
      - main
  
jobs:
  test:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ["3.8"]
    steps:
      - name: Install packages
        run: |
          pip install pathlib
          pip install andromeda-nlp
          pip install pytest
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test package
        run: |
          python ./tests/test_release.py
