name: build

on:
  workflow_dispatch

jobs:
  build:
    name: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Poetry
        uses: knowsuchagency/poetry-install@v2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build package
        run: |
          poetry env use python3
          poetry build
