name: release

on:
  workflow_dispatch

jobs:
  release:
    name: release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Install package
        run: |
          pip install andromeda-nlp
