name: build

on:
  workflow_dispatch

jobs:
  build:
    name: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install Pytest
        run: |
          pip install pytest
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install package dependencies
        run: |
          poetry install
      - name: Run Pytest
        run: |
          poetry env use python3
          poetry run pytest -v
      - name: Build package
        run: |
          poetry build
